version: '3'

services:

    billing_api_test:
        container_name: billing_api_test
        build:
            context: ./app
            dockerfile: Dockerfile.test
        networks:
            - backend
        environment:
            - DB_URL=billing_sql_test
            - DB_PASS=pass
            - DB_NAME=billdb
            - DB_PORT=3306
            - DB_USR=root
            
    billing_sql_test:
        sql_test_data: billing_sql_test
        build: ./db_scripts
        ports: 
            - "3408:3306"
        networks: 
            - backend
        volumes:
            - dbtest:/docker-entrypoint-initdb.d
            - intest:/root/app/in
            - container_data_test:/docker-entrypoint-initdb.d
        environment: 
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_PASSWORD=pass            
            - MYSQL_DATABASE=billdb
networks:
    backend:
volumes: 
    sql_test_data:
    dbtest:
    intest:
    
        
