version: '3'

services:
    api:
        container_name: billingapi
        build: ./app
        ports: 
            - "8081:5000"
        networks: 
            - backend
        environment: 
            - 'DB_URL=awsome_provider_sql_1:3306' 
            - 'DB_USR=ROOT' 
            - 'DB_PASS=pass' 
            - 'DB_NAME=billdb'
            - 'DB_PORT=3306'
            
            
    sql:
        container_name: mysql
        build: ./db_scripts
        ports: 
            - "3306:3306"        
        networks: 
            - backend
        volumes: 
            - 'container_data:/docker-entrypoint-initdb.d'        
        environment: 
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_USER=root
            - MYSQL_PASSWORD=pass            
            - MYSQL_DATABASE=billdb
networks:
    backend:
volumes: 
    container_data:
    
        
