version: '3'

services:

    tests:
        container_name: testapi
        build: ./app
        dockerfile: Dockerfile.test
        networks:
            - backend
        environment:
            - 'DB_URL=sql'
            - 'DB_PASS=pass'
            - 'DB_NAME=billdb'
            - 'DB_PORT=3408'
            
    sql:
        container_name: mysql
        build: ./db_scripts
        ports: 
            - "3408:3306"
        networks: 
            - backend
        volumes: 
            - 'container_data:/docker-entrypoint-initdb.d'        
        environment: 
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_USER=root
            - MYSQL_PASSWORD=pass            
            - MYSQL_DATABASE=billdb
networks:
    backend:
volumes: 
    container_data:
    
        
