version: '3'

services:
<<<<<<< HEAD
        # api:
        # container_name: billingapi
        #build: ./app
        #ports: 
        #    - "8081:5000"
        #networks: 
        #    - backend
        #environment: 
        #    - 'DB_URL=awsome_provider_sql_1'  
        #    - 'DB_PASS=pass' 
              # - 'DB_NAME=billdb'
              #      - 'DB_PORT=33060'
=======
    api:
        container_name: billingapi
        build: ./app
        ports: 
            - "8081:5000"
        networks: 
            - backend
        environment: 
            - 'DB_URL=mysql'
            - 'DB_USR=root'
            - 'DB_PASS=pass' 
            - 'DB_NAME=billdb'
            -
            - 'DB_PORT=33060'
>>>>>>> ccadbb36047d4ae5581542c5b701ccd6b0bd8684
            
            
    sql:
        container_name: mysql
        build: ./db_scripts
        ports: 
            - "33060:3306"
        networks: 
            - backend
        volumes: 
            - ./container_data:/var/lib/mysql
            - db:/docker-entrypoint-initdb.d
        environment: 
            - MYSQL_ROOT_PASSWORD=pass        
            - MYSQL_PASSWORD=pass            
            - MYSQL_DATABASE=billdb
networks:
    backend:
volumes: 
    container_data:
    db:
    
        
