version: '3'

services:
    sql:
        container_name: mysql
        build: ./db_scripts
        ports: 
            - "33060:3306"
        networks: 
            - backend
        volumes: 
            - ./container_data:/var/lib/mysql
            - db:/docker-entrypoint-initdb.d
        environment: 
            - MYSQL_ROOT_PASSWORD=pass        
            - MYSQL_PASSWORD=pass            
            - MYSQL_DATABASE=billdb
networks:
    backend:
volumes: 
    container_data:
    db:
    
        
