version: '2'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
     - "8082:5000"


  mysql:
    build:
        context: .
        dockerfile: Dockerfile.sql
    environment:
        MYSQL_DATABASE: "weight"
        MYSQL_USER: "root"
        MYSQL_PASSWORD: "pass"
        MYSQL_ROOT_PASSWORD: "pass"
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "3306:3306"
    volumes:
      -  ./DATA:/var/lib/mysql

volumes:
    DATA:
