version: '2' 
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
     - "5000:5000"
    volumes:
     - .:/app

  mysql:
    build:
        context: .
        dockerfile: Dockerfile.sql
    environment:
        MYSQL_ROOT_HOST: "%"
        MYSQL_ROOT_PASSWORD: "pass"
        MYSQL_DATABASE: "weight"
        MYSQL_USER: "web"
        MYSQL_PASSWORD: "pass"
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "3306:3306" 

volumes:
  mysql-db: