version: '2' 
services:
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    ports:
     - "5000:5000"
    volumes:
     - .:/app
    networks: 
    - backend
  mysql:
    build: 
      context: ./mysql/
      dockerfile: Dockerfile
      # ./mysql/Dockerfile
    ports:
      - "5005:3306" 
    networks: 
      - backend
    # environment:
    #     MYSQL_DATABASE: weight
    #     MYSQL_ROOT_PASSWORD: pass
    #     MYSQL_ROOT_HOST: '%'
    #     MYSQL_USER: root
    #     MYSQL_PASSWORD: pass
networks:
    backend: